### ISSUE TITLE
error run quant_test.py

### ISSUE THREAD

**Issue by Huangxingjx** [ARM-software/ML-KWS-for-MCU#66]
My command is :
python quant_test.py --model_architecture dnn --model_size_info 128 128 128  --dct_coefficient_count 10 --window_size_ms 40  --window_stride_ms 40 --checkpoint ../speech_commands_train/best/dnn_8476.ckpt-18000

but some error occured:
Traceback (most recent call last):
  File "quant_test.py", line 309, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\SOFTWARE\ANACONDA\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "quant_test.py", line 207, in main
    FLAGS.model_architecture, FLAGS.model_size_info)
  File "quant_test.py", line 80, in run_quant_inference
    is_training=False)
  File "D:\tmp\ML-KWS-for-MCU\quant_models.py", line 115, in create_model
    act_max, is_training)
  File "D:\tmp\ML-KWS-for-MCU\quant_models.py", line 163, in create_dnn_model
    if(act_max[i]!=0):
IndexError: list index out of range

why this error happened?

**Comment by navsuda** [comment]
Please provide act_max command-line parameter to quantize the model as per the instructions.
